### ISSUE TITLE
generateTempUserModel() doesn't inherit pre-save hooks

### ISSUE THREAD

**Issue by whitef0x0** [SaintDako/node-email-verification#9]
My temp user collection, which is generated with the `nev.generateTempUserModel(User);` command is not inheriting my pre-save mongoose hooks. 

Short of creating a new mongoose schema for my temporary user collection is there anyway this can be fixe?

**Comment by SaintDako** [comment]
hey,

if you look at the source of `generateTempUserModel`, only the schema's paths and methods are copied over. I'm guessing this doesn't include hooks of any kind (if it did, you wouldn't be running into this error).

so in that case, all that needs to be done is: find out where the hooks are stored in the Schema object, and then run a loop to copy them over. this is easy, and definitely doable, but I currently don't have Node installed and am busy for the rest of the day. if you want to take a look at it yourself and if you end up figuring it out, then submit a PR :) otherwise I'll try to get to it soon.
